export const MARKET_TABS = [
  { key: "chart", label: "Chart" },
  { key: "orderBook", label: "Order Book" },
  { key: "trades", label: "Trades" },
];

export const MARKET_INFO_TABS = [
  { key: "balances", label: "Balances" },
  { key: "positions", label: "Positions" },
  { key: "openOrders", label: "Open Orders" },
  { key: "twap", label: "TWAP" },
  { key: "tradeHistory", label: "Trade History" },
  { key: "funding", label: "Funding H" },
];

export const MARKET_SECTION_TABS = [
  { key: "markets", label: "Markets" },
  { key: "activity", label: "Activity" },
  { key: "holders", label: "Holders (354)" },
  { key: "traders", label: "Traders" },
  { key: "orders", label: "Order" },
  { key: "history", label: "History" },
];

export const ASSET_CATEGORIES = [
  { key: "all", label: "All Coins" },
  { key: "perps", label: "Perps" },
  { key: "spot", label: "Spot" },
  { key: "hip3", label: "HIP-3" },
  { key: "trending", label: "Trending" },
  { key: "favorites", label: "Favorites" },
];

export const CHART_TIMEFRAMES = [
  { key: "5m", label: "5m" },
  { key: "1h", label: "1h" },
  { key: "1d", label: "D" },
];

export const QUICK_TIMEFRAMES = [
  { key: "1s", label: "1s" },
  { key: "30s", label: "30s" },
  { key: "1m", label: "1m" },
  { key: "1h", label: "1h" },
  { key: "more", label: "More" },
];

export const INDICATOR_CHIPS = [
  "MA",
  "EMA",
  "BOLL",
  "SAR",
  "VOL",
  "MACD",
  "KDJ",
  "RSI",
  "StochRsi",
  "TRIX",
  "OBV",
];

export const ORDER_TICKET_TABS = [
  { key: "instant", label: "Instant" },
  { key: "market", label: "Market" },
  { key: "limit", label: "Limit" },
];

export const MARKET_ASSETS = [
  {
    id: "xpl-usdc",
    symbol: "XPL",
    quote: "USDC",
    pair: "XPL/USDC",
    name: "XPlus Network",
    type: "spot",
    leverage: "Spot",
    strict: true,
    categories: ["all", "spot", "hip3", "trending"],
    volume24h: 8_413_313,
    marketCap: 380_176_105,
    change24h: -10.38,
    price: 0.20068,
    contractAddress: "0x2c54...5a99",
    defaultSizeCap: 12_000,
    score: 0.89,
    holders: 354,
    top10: 18.38,
    liquidity: 20_230_000,
  },
  {
    id: "btc-usdc-perp",
    symbol: "BTC",
    quote: "USDC",
    pair: "BTC-USDC",
    name: "Bitcoin Perp",
    type: "perp",
    leverage: "40x",
    strict: true,
    categories: ["all", "perps", "trending"],
    volume24h: 8_240_000_000,
    marketCap: 0,
    change24h: -2.21,
    price: 84_286,
    contractAddress: "0xbTC0...perp",
    defaultSizeCap: 2,
  },
  {
    id: "eth-usdc-perp",
    symbol: "ETH",
    quote: "USDC",
    pair: "ETH-USDC",
    name: "Ethereum Perp",
    type: "perp",
    leverage: "25x",
    strict: true,
    categories: ["all", "perps"],
    volume24h: 2_790_000_000,
    marketCap: 0,
    change24h: -2.36,
    price: 2_743.2,
    contractAddress: "0xeTh0...perp",
    defaultSizeCap: 10,
  },
  {
    id: "sol-usdc-perp",
    symbol: "SOL",
    quote: "USDC",
    pair: "SOL-USDC",
    name: "Solana Perp",
    type: "perp",
    leverage: "20x",
    strict: true,
    categories: ["all", "perps", "trending"],
    volume24h: 927_000_000,
    marketCap: 0,
    change24h: -4.39,
    price: 126.26,
    contractAddress: "0xsoL0...perp",
    defaultSizeCap: 800,
  },
  {
    id: "hype-usdc-perp",
    symbol: "HYPE",
    quote: "USDC",
    pair: "HYPE-USDC",
    name: "Hyperliquid Perp",
    type: "perp",
    leverage: "10x",
    strict: true,
    categories: ["all", "perps", "trending"],
    volume24h: 848_000_000,
    marketCap: 0,
    change24h: -7.76,
    price: 33.794,
    contractAddress: "0xhyPe...perp",
    defaultSizeCap: 1200,
  },
  {
    id: "zec-usdc-perp",
    symbol: "ZEC",
    quote: "USDC",
    pair: "ZEC-USDC",
    name: "Zcash Perp",
    type: "perp",
    leverage: "10x",
    strict: false,
    categories: ["all", "perps"],
    volume24h: 652_000_000,
    marketCap: 0,
    change24h: -25.82,
    price: 490.24,
    contractAddress: "0xzec0...perp",
    defaultSizeCap: 600,
  },
  {
    id: "hype-usdc-spot",
    symbol: "HYPE",
    quote: "USDC",
    pair: "HYPE/USDC",
    name: "Hyperliquid Spot",
    type: "spot",
    leverage: "Spot",
    strict: false,
    categories: ["all", "spot", "hip3"],
    volume24h: 216_000_000,
    marketCap: 0,
    change24h: -7.75,
    price: 33.774,
    contractAddress: "0xhyPe...spot",
    defaultSizeCap: 3000,
  },
  {
    id: "btc-usdc-spot",
    symbol: "BTC",
    quote: "USDC",
    pair: "BTC/USDC",
    name: "Bitcoin Spot",
    type: "spot",
    leverage: "Spot",
    strict: false,
    categories: ["all", "spot"],
    volume24h: 161_000_000,
    marketCap: 0,
    change24h: -2.15,
    price: 84_259,
    contractAddress: "0xbTC0...spot",
    defaultSizeCap: 1.5,
  },
  {
    id: "xrp-usdc-perp",
    symbol: "XRP",
    quote: "USDC",
    pair: "XRP-USDC",
    name: "Ripple Perp",
    type: "perp",
    leverage: "20x",
    strict: true,
    categories: ["all", "perps"],
    volume24h: 155_000_000,
    change24h: -2.45,
    price: 1.9336,
    contractAddress: "0xXrP0...perp",
    defaultSizeCap: 30_000,
  },
  {
    id: "xyz100-usdc-perp",
    symbol: "XYZ100",
    quote: "USDC",
    pair: "XYZ100-USDC",
    name: "XYZ100 Index",
    type: "perp",
    leverage: "20x",
    strict: false,
    categories: ["all", "perps", "hip3"],
    volume24h: 116_000_000,
    change24h: 1.14,
    price: 24_342,
    contractAddress: "0xxyz0...perp",
    defaultSizeCap: 5,
  },
  {
    id: "fartcoin-usdc-perp",
    symbol: "FARTCOIN",
    quote: "USDC",
    pair: "FARTCOIN-USDC",
    name: "Fartcoin Perp",
    type: "perp",
    leverage: "10x",
    strict: false,
    categories: ["all", "perps", "trending"],
    volume24h: 102_000_000,
    change24h: -18.8,
    price: 0.20644,
    contractAddress: "0xfaRt...perp",
    defaultSizeCap: 400_000,
  },
  {
    id: "aster-usdc-perp",
    symbol: "ASTER",
    quote: "USDC",
    pair: "ASTER-USDC",
    name: "Aster Perp",
    type: "perp",
    leverage: "5x",
    strict: false,
    categories: ["all", "perps", "hip3"],
    volume24h: 75_900_000,
    change24h: -4.07,
    price: 1.1958,
    contractAddress: "0xasTe...perp",
    defaultSizeCap: 80_000,
  },
  {
    id: "pump-usdc-perp",
    symbol: "PUMP",
    quote: "USDC",
    pair: "PUMP-USDC",
    name: "Pump Perp",
    type: "perp",
    leverage: "10x",
    strict: false,
    categories: ["all", "perps", "trending"],
    volume24h: 65_900_000,
    change24h: -7.98,
    price: 0.002688,
    contractAddress: "0xpuMp...perp",
    defaultSizeCap: 1_200_000,
  },
];

export const TRADE_HISTORY_FALLBACK = [
  {
    id: "fallback-1",
    coin: "MOVE",
    time: "8/9/2025 - 16:21:18",
    size: "8,530 MOVE",
    direction: "Close Long",
    price: "0.14241",
    tradeValue: "1,214.76 USDC",
    pnl: "7.37 USDC",
    pnlRaw: -7.37,
    fee: "0.55 USDC",
  },
  {
    id: "fallback-2",
    coin: "MOVE",
    time: "8/9/2025 - 16:02:58",
    size: "8,530 MOVE",
    direction: "Close Long",
    price: "0.14241",
    tradeValue: "1,214.76 USDC",
    pnl: "7.37 USDC",
    pnlRaw: -7.37,
    fee: "0.55 USDC",
  },
  {
    id: "fallback-3",
    coin: "ETH",
    time: "8/9/2025 - 16:02:58",
    size: "1.5795 ETH",
    direction: "Close Long",
    price: "1,986.00",
    tradeValue: "3,101.00 USDC",
    pnl: "12.12 USDC",
    pnlRaw: 12.12,
    fee: "0.82 USDC",
  },
];

export const RECENT_TRADES_FALLBACK = [
  {
    id: "rt-1",
    price: 0.19906,
    size: 100.4,
    time: "01:06:47",
    direction: "SELL",
  },
  { id: "rt-2", price: 0.1991, size: 125, time: "01:06:47", direction: "BUY" },
  {
    id: "rt-3",
    price: 0.19916,
    size: 100.4,
    time: "01:06:34",
    direction: "BUY",
  },
  { id: "rt-4", price: 0.1992, size: 125, time: "01:05:54", direction: "BUY" },
  {
    id: "rt-5",
    price: 0.1993,
    size: 3_101,
    time: "01:05:43",
    direction: "SELL",
  },
  {
    id: "rt-6",
    price: 0.19948,
    size: 495.6,
    time: "01:05:38",
    direction: "BUY",
  },
  {
    id: "rt-7",
    price: 0.19963,
    size: 495.6,
    time: "01:05:30",
    direction: "BUY",
  },
  {
    id: "rt-8",
    price: 0.19974,
    size: 495.6,
    time: "01:05:25",
    direction: "BUY",
  },
  {
    id: "rt-9",
    price: 0.19966,
    size: 100.1,
    time: "01:05:25",
    direction: "SELL",
  },
];
