-- Migration: Optimize RLS policies to avoid repeated auth lookups and duplicate definitions
-- Generated by Codex CLI agent

BEGIN;

-- === Profiles RLS clean-up ===
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can insert their own profile." ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile." ON public.profiles;
DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can view their own profile" ON public.profiles;

CREATE POLICY "Public profiles are viewable by everyone."
  ON public.profiles
  FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Users can view their own profile"
  ON public.profiles
  FOR SELECT
  TO public
  USING (((SELECT auth.uid()) = id));

CREATE POLICY "Users can insert their own profile"
  ON public.profiles
  FOR INSERT
  TO public
  WITH CHECK (((SELECT auth.uid()) = id));

CREATE POLICY "Users can update their own profile"
  ON public.profiles
  FOR UPDATE
  TO public
  USING (((SELECT auth.uid()) = id))
  WITH CHECK (((SELECT auth.uid()) = id));

-- === Agents RLS optimization ===
DROP POLICY IF EXISTS "Users can view their own or published agents" ON public.agents;
DROP POLICY IF EXISTS "Users can insert their own agents" ON public.agents;
DROP POLICY IF EXISTS "Users can update their own agents" ON public.agents;
DROP POLICY IF EXISTS "Users can delete their own agents" ON public.agents;

CREATE POLICY "Users can view their own or published agents"
  ON public.agents
  FOR SELECT
  USING (
    (SELECT auth.uid()) = user_id
    OR published_at IS NOT NULL
  );

CREATE POLICY "Users can insert their own agents"
  ON public.agents
  FOR INSERT
  WITH CHECK (((SELECT auth.uid()) = user_id));

CREATE POLICY "Users can update their own agents"
  ON public.agents
  FOR UPDATE
  USING (((SELECT auth.uid()) = user_id))
  WITH CHECK (((SELECT auth.uid()) = user_id));

CREATE POLICY "Users can delete their own agents"
  ON public.agents
  FOR DELETE
  USING (((SELECT auth.uid()) = user_id));

-- === Assessments RLS optimization ===
DROP POLICY IF EXISTS "Users can view assessments for their agents" ON public.assessments;

CREATE POLICY "Users can view assessments for their agents"
  ON public.assessments
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.agents
      WHERE agents.id = assessments.agent_id
        AND agents.user_id = (SELECT auth.uid())
    )
  );

COMMIT;
