-- Migration: Add published_at metadata to agents and relax select policy for shared agents
-- Generated by Codex CLI agent

BEGIN;

-- Add a published_at column so creators can share agents to the community Explore tab
ALTER TABLE agents
ADD COLUMN IF NOT EXISTS published_at TIMESTAMPTZ;

-- Optional index to keep Explore tab queries quick
CREATE INDEX IF NOT EXISTS idx_agents_published_at
  ON agents (published_at DESC);

-- Update Row Level Security to allow authenticated users to read published agents
DROP POLICY IF EXISTS "Users can view their own agents" ON agents;

CREATE POLICY "Users can view their own or published agents"
  ON agents FOR SELECT
  USING (
    auth.uid() = user_id
    OR published_at IS NOT NULL
  );

COMMIT;

